Fix AttributeError on First return
When I ran dirsync for the first time I encountered the following
error, because there was an attempt to close a None object. The
result of calling write on a file is None.

```
dirsync -h
Creating user config file "/Users/aquilabdullah/.dirsync" ...Traceback (most recent call last):
  File "/Users/aquilabdullah/.virtualenvs/dirsync/bin/dirsync", line 11, in <module>
    load_entry_point('dirsync', 'console_scripts', 'dirsync')()
  File "/Users/aquilabdullah/devel/python/dirsync/dirsync/run.py", line 32, in from_cmdline
    f.close()
AttributeError: 'NoneType' object has no attribute 'close'
```